run-name: Build binary for linux arm64

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    steps:
      - uses: actions/checkout@v3

      -name: Setup Go
       uses: actions/setup-go@v4
       with:
        go-version: 1.24.5
      
      -name: Build
       run: GOOS=linux GOARCH=arm64 go build -o nginx-deployer_linux_arm_64